//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ykrasheniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public int Номер_заказа { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int КодПункта_выдачи { get; set; }
        public int Код_для_получения { get; set; }
        public int Статус_заказа { get; set; }
        public Nullable<int> КодПользователя { get; set; }
        public Nullable<int> КодТерминала { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктыВыдачи ПунктыВыдачи { get; set; }
        public virtual СтатусЗаказа СтатусЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
