//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ykrasheniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.Поставки = new HashSet<Поставки>();
            this.ПродукцияВЗаявке = new HashSet<ПродукцияВЗаявке>();
        }
    
        public int КодЗаявки { get; set; }
        public string Приоритет { get; set; }
        public string Статус { get; set; }
        public int КодПользователя { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияВЗаявке> ПродукцияВЗаявке { get; set; }
    }
}
