//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ykrasheniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставщики()
        {
            this.Поставки = new HashSet<Поставки>();
        }
    
        public int КодПоставщика { get; set; }
        public string НаименованиеКомпании { get; set; }
        public Nullable<int> ЮридическийАдрес { get; set; }
        public Nullable<int> ИНН { get; set; }
        public Nullable<int> КПП { get; set; }
        public string ФИОДиректора { get; set; }
        public Nullable<int> КодКонтакта { get; set; }
    
        public virtual Контакты Контакты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки { get; set; }
    }
}
