//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ykrasheniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        public int КодПоставки { get; set; }
        public int КодПродукции { get; set; }
        public int КодПоставщика { get; set; }
        public int КодЗаявки { get; set; }
        public int Количество { get; set; }
    
        public virtual Заявка Заявка { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
