//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ykrasheniya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Поставки = new HashSet<Поставки>();
            this.ПродукцияВЗаявке = new HashSet<ПродукцияВЗаявке>();
            this.ПродукцияВПродажах = new HashSet<ПродукцияВПродажах>();
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public int Единица_измерения { get; set; }
        public int Стоимость { get; set; }
        public int Размер_максимально_возможной_скидки { get; set; }
        public int КодПроизводителя { get; set; }
        public int КодПоставщика { get; set; }
        public int КодКатегорииТовара { get; set; }
        public int Действующая_скидка { get; set; }
        public int Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public int КодПродукции { get; set; }
    
        public virtual ЕдиницыИзмерения ЕдиницыИзмерения { get; set; }
        public virtual Категории Категории { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияВЗаявке> ПродукцияВЗаявке { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияВПродажах> ПродукцияВПродажах { get; set; }
        public virtual Производитель Производитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
